### ISSUE TITLE
Not displaying spells

### ISSUE THREAD

**Issue by mlawhun0114** [Sidoine/Ovale#385] opened 2017-12-08 20:44 UTC
Hello,
With the latest update(s), some of my spells no longer get displayed on the Ovale bar any longer.  I.e. for my feral druid, it no longer displays rake, shred, rip, and ferocious bite. It only displays for me to go into cat form, then use Ashamane's Frenzy only.  I had to roll back to version 7.3.0.3 in order for this addon to display all of my spells properly. Not sure if anyone else is getting the same thing as I am.

**Comment by Jierdan** [comment] 2017-12-08 21:28
> Not sure if anyone else is getting the same thing as I am.

Yep, same here. I am able to reproduce this bug just as described.

**Comment by velveteenheart** [comment] 2017-12-09 06:33
Same.

**Comment by cisox** [comment] 2017-12-09 14:07
Yeah, I'm getting the same behavior.

**Comment by kurkat** [comment] 2017-12-09 20:02
Yeah, I kinda went through the script pieces for ferals, and I don't think the problem is actually there (caveat, I'm no lua programmer, but there isn't a lot of difference in the T19 script and it still exhibits the new bug).

**Comment by Linkten** [comment] 2017-12-09 20:11
Same for me.

**Comment by Shadowjade** [comment] 2017-12-11 23:59
Experiencing the same thing.

**Comment by cisox** [comment] 2017-12-12 13:15
Is this fixed now for anyone else after having upgraded to 7.3.4? The fix was around opacity so perhaps it the opacity on the spells was just not showing them?

**Comment by Sidoine** [comment] 2017-12-15 07:57
It should have been fixed by shmoodude

**Closed** 2018-08-21 14:54 UTC
Labels: bug
