### ISSUE TITLE
Error in Power.lua

### ISSUE THREAD

**Issue by Saij** [Sidoine/Ovale#87] opened 2016-09-04 20:53 UTC
Class: Druid
Specc: Feral
Script: newest ShmooDude Script ^.^

Always seen this error with 5 CP ^.^

Message: Interface\AddOns\Ovale\Power.lua:722: attempt to compare number with nil
Time: 09/04/16 22:49:58
Count: 1531
Stack: [C]: ?
Interface\AddOns\Ovale\Power.lua:722: in function `TimeToPower'
Interface\AddOns\Ovale\SpellBook.lua:514: in function `GetTimeToSpell'
Interface\AddOns\Ovale\BestAction.lua:269: in function <Interface\AddOns\Ovale\BestAction.lua:209>
(tail call): ?
Interface\AddOns\Ovale\BestAction.lua:520: in function `?'
Interface\AddOns\Ovale\BestAction.lua:480: in function `RecursiveCompute'
Interface\AddOns\Ovale\BestAction.lua:459: in function `PostOrderCompute'
Interface\AddOns\Ovale\BestAction.lua:420: in function `Compute'
Interface\AddOns\Ovale\BestAction.lua:812: in function `?'
Interface\AddOns\Ovale\BestAction.lua:480: in function `RecursiveCompute'
Interface\AddOns\Ovale\BestAction.lua:459: in function `PostOrderCompute'
Interface\AddOns\Ovale\BestAction.lua:420: in function `Compute'
Interface\AddOns\Ovale\BestAction.lua:396: in function `GetAction'
Interface\AddOns\Ovale\Frame.lua:212: in function `OnUpdate'
Interface\AddOns\Ovale\Frame.lua:89: in function <Interface\AddOns\Ovale\Frame.lua:88>

Locals:

**Comment by kevindesmet** [comment] 2016-09-04 22:48
Possible duplicate of #78

**Comment by Saij** [comment] 2016-09-05 07:29
Quick Fix seems to be to add a check against nil.

`		if powerRate == nil then
			powerRate = 0
		end`

**Closed** 2016-09-05 13:23 UTC

**Comment by Saij** [comment] 2016-09-05 17:14
Little correction. 1 seems to be a better fallback value than 0 ^.^
