### ISSUE TITLE
Can't see DPS rotation

### ISSUE THREAD

**Issue by Ryulis** [Sidoine/Ovale#393] opened 2017-12-11 20:07 UTC
Ovale is  showing big cooldowns (Ashmane's frenzy, incarn and prepots)  but doesn't show SR/rip/rake/shred etc

**Comment by onehybrid** [comment] 2017-12-11 22:20
having the same problem after the update (hi btw)

**Comment by cisox** [comment] 2017-12-11 23:20
I believe this is a duplicate of #385

**Closed** 2017-12-11 23:28 UTC
