### ISSUE TITLE
Will the addon continue function and be updated ?

### ISSUE THREAD

**Issue by kAz0** [Sidoine/Ovale#446] opened 2018-05-30 18:19 UTC
Will the addon continue function and be updated ? I am casual in the game and the addon helps me a lot.
Would really like to know if the addon will get updated soon or in the future.Thanks for everything you do.

**Comment by ShmooDude** [comment] 2018-05-30 20:01
I'll probably work on it soon, but it won't function until it is.  I'm less experienced than Sidoine so may take a while.

**Comment by kAz0** [comment] 2018-05-30 20:46
Ive been following your feral druid scripts so much whole legion :D. Well i hope everything works out fine.And I hope he can give you permission so you can release updates.Many people depend on you :P thanks for making the game better for us.

**Comment by fwater** [comment] 2018-05-31 14:19
When to update the BFA version  @ShmooDude

**Comment by fwater** [comment] 2018-06-20 14:12
How long can we use it on PTR, or test it

**Comment by inforcer007** [comment] 2018-06-22 06:42
@mwojtkowski 

any chance you could upload those modified files ? totally don't understand that wall of text...

**Comment by mwojtkowski** [comment] 2018-06-22 09:14
@inforcer007 I never used GitHub before but I've forked this project and made modification so you can check that in my repo ( BfA branch ) copy dist and libs to your addon folder ( but like I said talents and spell ids still needs to be fixed )

**Comment by inforcer007** [comment] 2018-06-22 11:56
@mwojtkowski 

Thanks for that, ill try and figure that part out :)

**Comment by fwater** [comment] 2018-06-23 15:20
@mwojtkowski  target.Distance()  This function can't be judged or the distance is wrong （BFA)

**Comment by mwojtkowski** [comment] 2018-06-24 14:56
I've checked it on DH on beta and target.Distace() works fine no errors 

30y range checked with Throw Glaive

Include(ovale_common)
Include(ovale_demonhunter_spells)
AddIcon enemies=1 help=main specialization=vengeance
{
    if target.Distance() >= 30 Spell(infernal_strike)
}

**Comment by fwater** [comment] 2018-06-24 15:17
@mwojtkowski
I've checked it on paladin retribution


AddIcon enemies=1 help=main specialization=retribution
{
    if target.present() and HolyPower() <= 1 and target.Distance()<12 and not target.IsFriend() spell(wake_of_ashes)
    spell(judgment)
    Spell(templars_verdict)
    if holy_power<=3 Spell(blade_of_justice)
    if HolyPower() <= 4 Spell(crusader_strike)
}

the wake_of_ashes an't be judged or the distance is wrong

 But I write it like this works fine no errors

AddIcon enemies=1 help=main specialization=retribution
{
    if target.present() and HolyPower() <= 1 and target.InRange(templars_verdict) and not target.IsFriend() spell(wake_of_ashes)
    spell(judgment)
    Spell(templars_verdict)
    if holy_power<=3 Spell(blade_of_justice)
    if HolyPower() <= 4 Spell(crusader_strike)
}

I dont know why. distance() can't work I think

**Comment by mwojtkowski** [comment] 2018-06-24 16:13
@fwater 

Ok I think I know what you mean, unfortunately since target.Distance() is using LibRangeCheck-2.0 it can check only 5, 6, 8, 10, 15, 20, 25, 30, 35 38, 40, 45, 50, 55, 60, 70, 80, 90, 100 yards  and WoA is 12y you need to check for 10y or use InRange(blade_of_justice) since that spell has 12y range same as WoA.

**Comment by fwater** [comment] 2018-06-24 16:34
@mwojtkowski  InRange(blade_of_justice) is ok
buf 7.35 if target.Distance()<12 spell(wake_of_ashes) works well.
I think LibRangeCheck-2.0 need to be fixed in bfa.
I am writing the cycle of talents, and I may find more BUG.

**Comment by fwater** [comment] 2018-06-25 14:38
Thanks for your work.  PreviousGCDSpell() work now!
today I play the Fury. spell(rampage)  
the talent I chose [Carnage] or [Frothing Berserker]
the ovale spell(rampage)   Always show up rampage when the rage is 85.  not the rage is 75 or 95
maybe something other bugs cause.

**Comment by ShmooDude** [comment] 2018-06-26 03:40
Should finally be able to work on this soon (had some carpel tunnel so haven't been working on it lately).  Good job getting it started mwojtkowski.

I'm planning on cutting it down / cleaning up unnecessary code as much as possible, especially as it regards to auras (ferals probably know what I'm talking about but no one else).  Helps performance a lot for the more complicated scripts.

**Comment by mwojtkowski** [comment] 2018-06-26 05:45
thanks for letting us know what's going on @ShmooDude, atm I'm working on updating spells / talents for each class and adding them to SimC import

**Comment by fwater** [comment] 2018-06-26 14:21
DK can't work  need to be fixed （bfa)

**Comment by mwojtkowski** [comment] 2018-06-27 18:01
@fwater yes error on DK was caused by RUNE_TYPE_UPDATE which was removed from API. 
Updated warrior spells and talents ( default rotation script is broken, I'm waiting for SimC profile to update it  )

**Comment by fwater** [comment] 2018-06-28 04:06
@mwojtkowski
PreviousGCDSpell   can't work for monk
    if  not PreviousGCDSpell(tiger_palm)  and chi() <4 spell(tiger_palm)
    if not PreviousGCDSpell(blackout_kick) Spell(blackout_kick)

**Comment by mwojtkowski** [comment] 2018-06-29 00:48
I've checked on Live and PreviousGCDSpell is also broken on Live 
 
after some testing this.next.PushGCDSpellId(spellId) fires so randomly for instant spells that maybe once in 10 spells will trigger it (but works for spells with cast times like Shadow/Frost Bolt ).

After some more testing moved  this.next.PushGCDSpellId(spellId) to UpdateLastSpellcast from ApplySpell it fixes problem PreviousGCDSpell

While in ApplySpell it would fire on every Icon update but with UpdateLastSpellcast it will fire only on UNIT_SPELLCAST events

**Comment by mwojtkowski** [comment] 2018-06-29 10:13
@ShmooDude I saw that Ovale scans your target and all visible nameplates for auras would restricting it to current target and only player own spells help ?

**Comment by ShmooDude** [comment] 2018-07-06 23:17
@mwojtkowski I found that simply restricting it to player spells (except on yourself) was probably enough.

Could you upload your working directory somewhere?  I think I have my typescript messed up and get a ton of errors when I simply use your code from github.

**Comment by mwojtkowski** [comment] 2018-07-07 09:18
@ShmooDude if you're talking about errors from 'npm run prepare' than yes there will be errors because @wowts/wow-mock is not updated for 8.0. It will still 'compile' it without problems.

To remove errors you need to add add:

@wowts/wow-mock/index.d.ts
```
export declare function CombatLogGetCurrentEventInfo(): any[];
export declare function GetMacroSpell(slot: number): number;
```
and then use 
```
import { CombatLogGetCurrentEventInfo } from "@wowts/wow-mock";
```

other errors are from unused variables in @wowts/ace_* libs ( can be ignored by setting "noUnusedLocals": false in tsconfig.lua.json )

[Ovale.zip](https://github.com/Sidoine/Ovale/files/2172605/Ovale.zip)
it has modified functions in @wowts/wow-mock/index.d.ts

**Comment by ShmooDude** [comment] 2018-07-08 02:32
Thanks, I actually had a lot more problems than that so this fixed it.

**Comment by ShmooDude** [comment] 2018-07-09 04:57
@mwojtkowski I'm getting errors in all the for loops:
```
    for (const [debuffType] of pairs(DEBUFF_TYPE)) {
        let siDebuffType = strlower(debuffType);
        SPELLINFO_DEBUFF_TYPE[siDebuffType] = debuffType;
    }
```
is generating:
`[ts] Argument of type 'string | number' is not assignable to parameter of type 'string'. Type 'number' is not assignable to type 'string'`

Any ideas why?  I can still code with it like that but makes it much harder to look for real errors.

**Comment by mwojtkowski** [comment] 2018-07-09 05:32
@ShmooDude It is caused by LuaObj interface if you want to get rid of 'string | number' errors change:
```
export declare function pairs<T>(a: LuaObj<T>): [keyof typeof a, T][];
export declare function pairs<T>(a: T): [keyof typeof a, any][];
```
to
```
export declare function pairs<T>(a: LuaObj<T>): [string, T][];
export declare function pairs<T>(a: T): [string, any][];
```
in Ovale\node_modules\@wowts\lua\index.d.ts

**Comment by fwater** [comment] 2018-07-13 16:21
@mwojtkowski 
When you are on a PVP server
Entering the arena
He will report an error and continue to report an error and cannot close
it is currently unable to enter the arena


Message: ...ngeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1343: Attempt to register unknown event "GLYPH_ADDED"
Time: Fri Jul 13 23:53:14 2018
Count: 1
Stack: ...ngeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1343: Attempt to register unknown event "GLYPH_ADDED"
[C]: in function `RegisterEvent'
...ngeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1343: in function `activate'
...ngeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1389: in main chunk

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "GLYPH_ADDED"

Message: Frame MYSLOT_ReportFrame_EditBox: Unknown script element OnClick
Time: Fri Jul 13 23:53:14 2018
Count: 4

Message: (null)
Time: Fri Jul 13 23:53:14 2018
Count: 4

Message: Interface\AddOns\Ovale\dist\Power.lua:393: attempt to index local 'powerInfo' (a nil value)
Time: Sat Jul 14 00:14:44 2018
Count: 680
Stack: Interface\AddOns\Ovale\dist\Power.lua:393: attempt to index local 'powerInfo' (a nil value)
Interface\AddOns\Ovale\dist\Power.lua:393: in function `UpdatePower'
Interface\AddOns\Ovale\dist\Power.lua:356: in function `?'
...kada\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...kada\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...kada\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...face\AddOns\Ovale\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...face\AddOns\Ovale\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by fwater** [comment] 2018-07-20 06:20
@mwojtkowski
I've used your latest version. The arena is not wrong, but entering the arena or coming out will result in the invalidation of the code, and /reload must be restored.

**Comment by mwojtkowski** [comment] 2018-07-20 09:55
Looking at your previous error it was caused by old LibRangeCheck library that was included in Skada so I assume you didn't update libraries that Ovale use ( I don't upload them to my repo )

Try this ( copy this to Ovale folder )
[libs.zip](https://github.com/Sidoine/Ovale/files/2213361/libs.zip)

**Comment by Jevnaker** [comment] 2018-07-21 16:12
the addon itself works perfectly after i downloaded that ovale.zip and lib thing but ovale keeps complaining about some talents missing or something like sidewinder talent on my hunter.

**Comment by fwater** [comment] 2018-07-22 05:20
@Jevnaker   scripts 
Do not delete some of the magic ID in the previous version

**Comment by Jevnaker** [comment] 2018-07-22 20:29
magic id what is that?

**Comment by fwater** [comment] 2018-07-23 04:54
spell id

**Comment by Jevnaker** [comment] 2018-07-24 14:32
ok is that an folder or what?

**Comment by Jevnaker** [comment] 2018-07-29 10:57
i have tried different stuff but i still keep getting  ovalecompile (unknown spell with id xxxx used in spelll xxxx) and i am not sure how to fix it.

**Closed** 2018-08-21 14:36 UTC
