### ISSUE TITLE
[9.0.19] name() function no longer parses target or name parameter (localized text) to compare

### ISSUE THREAD

**Issue by sirTribble** [Sidoine/Ovale#716] opened 2020-12-03 17:13 UTC
sample code

AddFunction DungeonBosses
{
boss1.Name("Жрица Алун'за")
}

**Comment by ultijlam** [comment] 2020-12-04 14:27
This is a duplicate of #715 and is caused by the same underlying reason.

**Comment by sirTribble** [comment] 2020-12-04 18:28
name parameter not parsed as well.

**Comment by Sidoine** [comment] 2020-12-07 21:03
You should use boss1.name() == "whatever"

**Closed by Sidoine** 2020-12-07 21:03 UTC
