### ISSUE TITLE
Unable to download update through CurseForge

### ISSUE THREAD

**Issue by RWexelblat** [Sidoine/Ovale#736] opened 2020-12-14 16:46 UTC
When I click update it seems to start downloading but terminates with the message "An error has occurred. Please check your  connection and try again."

I have about a dozen addons, many of which have had recent updates but this is the only one that gives me this message. (I can download manually from the ovale website.)

**Comment by Sidoine** [comment] 2020-12-15 13:26
Do somebody else have this problem?
I don't use the Curseforge client anymore but I don't see why it shouldn't work for this Addon.

**Comment by Guy5491** [comment] 2020-12-16 09:12
i have the same problem since 9.0.20 and the same results i am on macOS Big Sur version 11.0.1

**Comment by Sidoine** [comment] 2020-12-16 13:30
That's strange. I'll install the Curseforge client to test this. I use WoWUp if you want to test another client.

**Comment by HunterFearne** [comment] 2020-12-16 15:30
Same here - unable to update or download it from Curseforge.  All other addons updating fine.

**Comment by RWexelblat** [comment] 2020-12-16 16:52
Interesting. OSX refused to let me open WowUP saying it was not able to
check it for malicious software.

**Comment by Guy5491** [comment] 2020-12-16 17:10
i suppose you have reason  i put big sur (macOS version 11.0.1) at the same time you realize 9.0.21 but all other add-on  accept to be updated, and i have 80 add-ons , only ovale don't accept very curious

**Comment by Guy5491** [comment] 2020-12-16 17:29
i just try with wowup now,  and it is good ovale accept to be updated with your latest version you realize 4 hours ago version 9.0.26
sorry for my bad english

**Comment by Guy5491** [comment] 2020-12-16 17:33
and for RWexelblat before open wowup click  on alt and then you will be able to open wow by clicking open in the menu

**Comment by ultijlam** [comment] 2020-12-19 20:57
I can't reproduce this issue with the CurseForge client.

**Comment by jgleigh** [comment] 2020-12-19 21:43
I'm having the same issue with the CurseForge client.

**Comment by Guy5491** [comment] 2020-12-20 08:06
to day it is impossible to update ovale to 9.0.28 both on curse and Wowup

**Comment by jgleigh** [comment] 2021-01-05 17:56
Still an issue with every new update.

**Comment by Guy5491** [comment] 2021-01-05 18:49
i am oblige at every update to do it manualy from curse forge, its the same with wowup  sorry for sidoine but perhaps Big Sur (mac os) is very hard for security

**Comment by jgleigh** [comment] 2021-01-05 18:55
I'm still running Catalina and this is the only addon that Curseforge has issues with updating.

**Comment by Sidoine** [comment] 2021-01-05 20:40
It should be fixed in the next release

**Comment by Guy5491** [comment] 2021-01-06 19:02
its the same for 9.02.34, always manually

**Comment by Sidoine** [comment] 2021-01-17 14:18
Do you still have the bug? It should be solved.

**Comment by RWexelblat** [comment] 2021-01-17 14:25
It's working now. Thanks

**Comment by Guy5491** [comment] 2021-01-17 14:28
it's working also but don't forget to update curse forge app.
thanks Sidoine

**Comment by jgleigh** [comment] 2021-01-17 16:44
Working now.

**Closed** 2021-01-17 21:54 UTC
